name: horse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Verify Node.js Installation
      run: node --version
    - name: Setup Newman
      run: npm install -g newman
    - name: Verify Newman Installation
      run: newman --version
    - name: Verify Newman Installation
      run: newman --version
    - name: Launch application console
      run: start ./Console.exe
    - name: Running Postman Tests
      run: newman run ./Postman/rest-api-delphi.postman_collection.json --environment ./Postman/horse-console-application.postman_environment.json --insecure
