name: horse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Verify Node.js Installation
      run: node --version
    - name: Setup Newman
      run: npm install -g newman
    - name: Verify Newman Installation
      run: newman --version